### ISSUE TITLE
Unable to run CallPeaks

### ISSUE THREAD

**Issue by JonathanNoonan** [timoast/signac#739]
Hi Tim,

I am currently unable to successfully run the CallPeaks function with my own data, or with the test 10k PBMC data as per the Multiome Vignette. Your help would be much appreciated. 

Regardless of the data set used, I get the following error:

> peaks <- CallPeaks(pbmc, macs2.path = "/Users/JonathanNoonan/Library/Python/3.8/bin/macs2")
Traceback (most recent call last):
  File "/Users/JonathanNoonan/Library/Python/3.8/bin/macs2", line 653, in <module>
    main()
  File "/Users/JonathanNoonan/Library/Python/3.8/bin/macs2", line 49, in main
    from MACS2.callpeak_cmd import run
  File "/Users/JonathanNoonan/Library/Python/3.8/lib/python/site-packages/MACS2/callpeak_cmd.py", line 23, in <module>
    from MACS2.OptValidator import opt_validate
  File "/Users/JonathanNoonan/Library/Python/3.8/lib/python/site-packages/MACS2/OptValidator.py", line 20, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 242, in init MACS2.IO.Parser
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
cannot open file '/var/folders/84/32q7007912d2jzspxwh5mxqm0000gn/T//RtmpfIkBAS/SeuratProject_peaks.narrowPeak': No such file or directoryError in file(file, "rt") : cannot open the connection

**Using  my own data:**

# WT {.tabset}
## Prepare {.tabset}
```{r}
# load the RNA and ATAC data
Raw.WT <- Read10X("/Users/JonathanNoonan/Desktop/Multiome/CellRanger/ARC Run/2nd Experiment/WT2_outs/filtered_feature_bc_matrix/")

WT_fragpath <- "/Users/JonathanNoonan/Desktop/Multiome/CellRanger/ARC Run/2nd Experiment/WT2_outs/atac_fragments.tsv.gz"

# get gene annotations for mm10
annotation <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79)
seqlevelsStyle(annotation) <- "UCSC"
genome(annotation) <- "mm10"


# create a Seurat object containing the RNA adata
WT <- CreateSeuratObject(counts = Raw.WT$`Gene Expression`,
  assay = "RNA")

# create ATAC assay and add it to the object
WT[["ATAC"]] <- CreateChromatinAssay(counts = Raw.WT$Peaks,
  sep = c(":", "-"), fragments = WT_fragpath, annotation = annotation)
```

```{r}
#ATAC QC
DefaultAssay(WT) <- "ATAC"

WT <- NucleosomeSignal(WT)
WT <- TSSEnrichment(WT)


VlnPlot(object = WT,
  features = c("nCount_RNA", "nCount_ATAC", "TSS.enrichment", "nucleosome_signal"),
  ncol = 4,
  pt.size = 0)

WT$nucleosome_group <- ifelse(WT$nucleosome_signal > 2, 'NS > 2', 'NS < 2')
FragmentHistogram(object = WT, group.by = 'nucleosome_group', region = 'chr1-1-10000000')


# filter out low quality cells
WT <- subset(
  x = WT,
  subset = nCount_ATAC < 60000 &
       nCount_ATAC > 1000 &
    nucleosome_signal < 2 &
    TSS.enrichment > 4)


VlnPlot(object = WT,
  features = c("nCount_RNA", "nCount_ATAC", "TSS.enrichment", "nucleosome_signal"),
  ncol = 4,
  pt.size = 0)
```

## Peak Calling
```{r}
WT.Peaks <- CallPeaks(WT, macs2.path = "/Users/JonathanNoonan/Library/Python/3.8/bin/macs2", outdir = "/Users/JonathanNoonan/Desktop/Multiome/R_Analysis/MACSouts")
```

**Using example data**
```{r}
# load the RNA and ATAC data
counts <- Read10X_h5("/Users/JonathanNoonan/Desktop/Multiome/Test_Data/pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5")
fragpath <- "/Users/JonathanNoonan/Desktop/Multiome/Test_Data/pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz"


# get gene annotations for hg38
annotation <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotation) <- "UCSC"
genome(annotation) <- "hg38"

# create a Seurat object containing the RNA adata
pbmc <- CreateSeuratObject(
  counts = counts$`Gene Expression`,
  assay = "RNA"
)

# create ATAC assay and add it to the object
pbmc[["ATAC"]] <- CreateChromatinAssay(
  counts = counts$Peaks,
  sep = c(":", "-"),
  fragments = fragpath,
  annotation = annotation
)

DefaultAssay(pbmc) <- "ATAC"

pbmc <- NucleosomeSignal(pbmc)
pbmc <- TSSEnrichment(pbmc)

VlnPlot(
  object = pbmc,
  features = c("nCount_RNA", "nCount_ATAC", "TSS.enrichment", "nucleosome_signal"),
  ncol = 4,
  pt.size = 0
)


# filter out low quality cells
pbmc <- subset(
  x = pbmc,
  subset = nCount_ATAC < 100000 &
    nCount_RNA < 25000 &
    nCount_ATAC > 1000 &
    nCount_RNA > 1000 &
    nucleosome_signal < 2 &
    TSS.enrichment > 1
)
pbmc


# call peaks using MACS2
peaks <- CallPeaks(pbmc, macs2.path = "/Users/JonathanNoonan/Library/Python/3.8/bin/macs2")
```

```
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] BSgenome.Hsapiens.UCSC.hg38_1.4.3  EnsDb.Hsapiens.v86_2.99.0          BSgenome.Mmusculus.UCSC.mm10_1.4.0
 [4] BSgenome_1.60.0                    rtracklayer_1.52.0                 Biostrings_2.60.1                 
 [7] XVector_0.32.0                     EnsDb.Mmusculus.v79_2.99.0         ensembldb_2.16.3                  
[10] AnnotationFilter_1.16.0            GenomicFeatures_1.44.0             AnnotationDbi_1.54.1              
[13] Biobase_2.52.0                     Signac_1.3.0                       Seurat_4.0.3                      
[16] SeuratObject_4.0.2                 GenomicRanges_1.44.0               GenomeInfoDb_1.28.1               
[19] IRanges_2.26.0                     S4Vectors_0.30.0                   BiocGenerics_0.38.0               

loaded via a namespace (and not attached):
  [1] utf8_1.2.2                  reticulate_1.20-9001        tidyselect_1.1.1           
  [4] RSQLite_2.2.7               htmlwidgets_1.5.3           grid_4.1.0                 
  [7] docopt_0.7.1                BiocParallel_1.26.1         Rtsne_0.15                 
 [10] munsell_0.5.0               codetools_0.2-18            ica_1.0-2                  
 [13] future_1.21.0               miniUI_0.1.1.1              colorspace_2.0-2           
 [16] filelock_1.0.2              knitr_1.33                  rstudioapi_0.13            
 [19] ROCR_1.0-11                 tensor_1.5                  listenv_0.8.0              
 [22] labeling_0.4.2              MatrixGenerics_1.4.0        slam_0.1-48                
 [25] GenomeInfoDbData_1.2.6      polyclip_1.10-0             bit64_4.0.5                
 [28] farver_2.1.0                parallelly_1.27.0           vctrs_0.3.8                
 [31] generics_0.1.0              xfun_0.24                   biovizBase_1.40.0          
 [34] BiocFileCache_2.0.0         lsa_0.73.2                  ggseqlogo_0.1              
 [37] R6_2.5.0                    hdf5r_1.3.3                 bitops_1.0-7               
 [40] spatstat.utils_2.2-0        cachem_1.0.5                DelayedArray_0.18.0        
 [43] assertthat_0.2.1            promises_1.2.0.1            BiocIO_1.2.0               
 [46] scales_1.1.1                nnet_7.3-16                 gtable_0.3.0               
 [49] globals_0.14.0              goftest_1.2-2               rlang_0.4.11               
 [52] RcppRoll_0.3.0              splines_4.1.0               lazyeval_0.2.2             
 [55] dichromat_2.0-0             checkmate_2.0.0             spatstat.geom_2.2-2        
 [58] BiocManager_1.30.16         yaml_2.2.1                  reshape2_1.4.4             
 [61] abind_1.4-5                 backports_1.2.1             httpuv_1.6.1               
 [64] Hmisc_4.5-0                 tools_4.1.0                 ggplot2_3.3.5              
 [67] ellipsis_0.3.2              spatstat.core_2.3-0         RColorBrewer_1.1-2         
 [70] ggridges_0.5.3              Rcpp_1.0.7                  plyr_1.8.6                 
 [73] base64enc_0.1-3             progress_1.2.2              zlibbioc_1.38.0            
 [76] purrr_0.3.4                 RCurl_1.98-1.3              prettyunits_1.1.1          
 [79] rpart_4.1-15                deldir_0.2-10               pbapply_1.4-3              
 [82] cowplot_1.1.1               zoo_1.8-9                   SummarizedExperiment_1.22.0
 [85] ggrepel_0.9.1               cluster_2.1.2               magrittr_2.0.1             
 [88] data.table_1.14.0           scattermore_0.7             lmtest_0.9-38              
 [91] RANN_2.6.1                  SnowballC_0.7.0             ProtGenerics_1.24.0        
 [94] fitdistrplus_1.1-5          matrixStats_0.59.0          evaluate_0.14              
 [97] hms_1.1.0                   patchwork_1.1.1             mime_0.11                  
[100] xtable_1.8-4                XML_3.99-0.6                jpeg_0.1-9                 
[103] sparsesvd_0.2               gridExtra_2.3               compiler_4.1.0             
[106] biomaRt_2.48.2              tibble_3.1.3                KernSmooth_2.23-20         
[109] crayon_1.4.1                htmltools_0.5.1.1           mgcv_1.8-36                
[112] later_1.2.0                 Formula_1.2-4               tidyr_1.1.3                
[115] DBI_1.1.1                   tweenr_1.0.2                dbplyr_2.1.1               
[118] MASS_7.3-54                 rappdirs_0.3.3              Matrix_1.3-4               
[121] cli_3.0.1                   igraph_1.2.6                pkgconfig_2.0.3            
[124] GenomicAlignments_1.28.0    foreign_0.8-81              plotly_4.9.4.1             
[127] spatstat.sparse_2.0-0       xml2_1.3.2                  VariantAnnotation_1.38.0   
[130] stringr_1.4.0               digest_0.6.27               sctransform_0.3.2          
[133] RcppAnnoy_0.0.18            spatstat.data_2.1-0         rmarkdown_2.9              
[136] leiden_0.3.8                fastmatch_1.1-3             htmlTable_2.2.1            
[139] uwot_0.1.10                 restfulr_0.0.13             curl_4.3.2                 
[142] shiny_1.6.0                 Rsamtools_2.8.0             rjson_0.2.20               
[145] lifecycle_1.0.0             nlme_3.1-152                jsonlite_1.7.2             
[148] viridisLite_0.4.0           fansi_0.5.0                 pillar_1.6.1               
[151] lattice_0.20-44             KEGGREST_1.32.0             fastmap_1.1.0              
[154] httr_1.4.2                  survival_3.2-11             glue_1.4.2                 
[157] qlcMatrix_0.9.7             png_0.1-7                   bit_4.0.4                  
[160] ggforce_0.3.3               stringi_1.7.3               blob_1.2.2                 
[163] latticeExtra_0.6-29         memoise_2.0.0               dplyr_1.0.7                
[166] irlba_2.3.3                 future.apply_1.7.0         

```

**Comment by timoast** [comment]
It looks like there could be an issue with your MACS2 installation, can you confirm that you are able to successfully run MACS2 outside of Signac/R?

**Comment by JonathanNoonan** [comment]
Hi Tim - You were absolutely right. I have no experience with Python and, while i'm familiar with R...thats about where my expertise end. 

It turns out the issue was actually that the default version of Numpy being accessed by Python3 was not up to date. I've now updated Numpy and it seems to work fine now. No issues what so ever. 

Thank you very much, as always, for your stellar work and speedy assistance!

**Comment by aj088** [comment]
I encountered a similar issue, can you inform what version of numpy you have updated to? Thanks
